### ISSUE TITLE
How to play sound in a loop without hearable gap

### ISSUE THREAD

**Issue by JoeKingKong** [owoudenberg/soundtouch.net#10]
Hi,
I tryed to find out how to play a file in a loop without gap. Unfortunately the PlaybackStopped event seams to imply a Stop() on the player so a new Play() is hearable. 

Thanks for providing me the right solution concept.

**Comment by owoudenberg** [comment]
The sound-touch library deals with adjusting playback speed and pitch. The playback of audio depends on your audio library. When using NAudio, it would be best to search their documentation on how to adequately loop the audio.
