### ISSUE TITLE
BPM Detection example

### ISSUE THREAD

**Issue by DenkingOfficial** [owoudenberg/soundtouch.net#16]
Hi, can you please show me an example for BpmDetect?
I'm making a tool for analyzing Key and BPM of WAV files but I can't figure out how to use this library for BPM detection
I will be very grateful if you can help me

**Comment by owoudenberg** [comment]
The SoundStretch application already contains an example for calculating the BPM. 
See the Program.DetectBpm method for how this is implemented.

You can run the SoundStretch application from the commandline:
soundstretch <infilename> -bpm

https://github.com/owoudenberg/soundtouch.net/blob/98e5b8fd2f8efed0ddf7c8f66b435bfb231659dc/src/SoundStretch/Program.cs#L165
