### ISSUE TITLE
Any possibility of making the licensing more relaxed?

### ISSUE THREAD

**Issue by jtorjo** [owoudenberg/soundtouch.net#8]
Hi,

I love the lib! I'd like to use it in a commercial app, and unfortunately I need to recompile it (and I can't do it with the current licensing), since I need to use it in UWP, and I've tweaked naudio for my needs.

Would that be possible?

Best,
John

**Comment by owoudenberg** [comment]
Could you indicate why you need to have it recompiled? The provided package should work in a UWP environment.
If you need to make modifications, you can contribute to the project by making a pull-request. I can then incorporate your changes into the source-code.

**Comment by jtorjo** [comment]
Hi,
What you say makes sense.
Long story short, I've managed to use the original C++ lib, so I don't need relaxing your lib anymore. Thanks again!
 
My rationale for the request:
The library indeed should work on a UWP environment, but it relies on naudio. And I have already tweaked naudio myself to make it work with my current app, so using your lib would cause conflicts.
